// <auto-generated />
namespace Loyalty.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CardStatusMigration5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CardStatusMigration5));
        
        string IMigrationMetadata.Id
        {
            get { return "201606240856215_Card-Status-Migration-5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
